// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo2dY0fzJNgdSD9tj0uUriZ-hIfNd5-n8',
    appId: '1:744731343270:web:8adf48622b57107eb97767',
    messagingSenderId: '744731343270',
    projectId: 'chat-app-007-37009',
    authDomain: 'chat-app-007-37009.firebaseapp.com',
    storageBucket: 'chat-app-007-37009.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnAfjPdG_5mSlGJH7DL1q-G288AILlNaw',
    appId: '1:744731343270:android:32eed0bfeb9f4e98b97767',
    messagingSenderId: '744731343270',
    projectId: 'chat-app-007-37009',
    storageBucket: 'chat-app-007-37009.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9u9Oh5DxyWGlUhakdGxOGHO1Hb8Mrj5g',
    appId: '1:744731343270:ios:44eb36afe3a718adb97767',
    messagingSenderId: '744731343270',
    projectId: 'chat-app-007-37009',
    storageBucket: 'chat-app-007-37009.firebasestorage.app',
    iosBundleId: 'com.example.messenger.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9u9Oh5DxyWGlUhakdGxOGHO1Hb8Mrj5g',
    appId: '1:744731343270:ios:44eb36afe3a718adb97767',
    messagingSenderId: '744731343270',
    projectId: 'chat-app-007-37009',
    storageBucket: 'chat-app-007-37009.firebasestorage.app',
    iosBundleId: 'com.example.messenger.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo2dY0fzJNgdSD9tj0uUriZ-hIfNd5-n8',
    appId: '1:744731343270:web:6eff87759019e753b97767',
    messagingSenderId: '744731343270',
    projectId: 'chat-app-007-37009',
    authDomain: 'chat-app-007-37009.firebaseapp.com',
    storageBucket: 'chat-app-007-37009.firebasestorage.app',
  );
}
